-- Generated by easyunicornpkg ©Commandcracker
-- https://github.com/SquidDev-CC/mbs

local package = {}
package.name = "mbs"
package.desc = "A Mildly Better Shell for ComputerCraft"
package.instdat = {}
package.instdat.repo_owner = "SquidDev-CC"
package.instdat.repo_name = "mbs"
package.instdat.repo_ref = "master"
package.instdat.filemaps = {}

--[[
    TODO: add, when string provider is there and multiple pkgType are there
    Content: assert(loadfile("mbs.lua", _ENV))('startup', "mbs.lua")

    package.instdat.filemaps["???"] = "/startup/00_mbs.lua"
]]

package.instdat.filemaps["mbs.lua"] = "/bin/mbs.lua"

package.instdat.filemaps["lib/readline.lua"] = "/opt/mbs/lib/readline.lua"
package.instdat.filemaps["lib/scroll_window.lua"] = "/opt/mbs/lib/scroll_window.lua"
package.instdat.filemaps["lib/stack_trace.lua"] = "/opt/mbs/lib/stack_trace.lua"

package.instdat.filemaps["modules/lua.lua"] = "/opt/mbs/modules/lua.lua"
package.instdat.filemaps["modules/pager.lua"] = "/opt/mbs/modules/pager.lua"
package.instdat.filemaps["modules/readline.lua"] = "/opt/mbs/modules/readline.lua"
package.instdat.filemaps["modules/shell.lua"] = "/opt/mbs/modules/shell.lua"

package.instdat.filemaps["bin/clear.lua"] = "/opt/mbs/bin/clear.lua"
package.instdat.filemaps["bin/lua.lua"] = "/opt/mbs/bin/lua.lua"
package.instdat.filemaps["bin/shell-worker.lua"] = "/opt/mbs/bin/shell-worker.lua"
package.instdat.filemaps["bin/shell.lua"] = "/opt/mbs/bin/shell.lua"

package.script = {}
package.script.postinstall = [[
  settings.set("mbs.install_path", "/opt/mbs")
  settings.save()
]]
package.script.postremove = [[
  settings.unset("mbs.install_path")
  settings.save()
]]

package.pkgType = "com.github"
package.unicornSpec = "v1.0.0"

return package
