-- Generated by easyunicornpkg ©Commandcracker
-- https://github.com/SquidDev-CC/mbs

local package = {}
package.name = "mbs"
package.desc = "A Mildly Better Shell for ComputerCraft"
package.instdat = {}
package.instdat.repo_owner = "SquidDev-CC"
package.instdat.repo_name = "mbs"
package.instdat.repo_ref = "master"
package.instdat.filemaps = {}

printError('You need to create "/startup/00_mbs.lua" with to content: assert(loadfile("mbs.lua", _ENV))(\'startup\', "mbs.lua")')
printError('or run /mbs install')
--[[
    TODO: add, when string provider is there and multiple pkgType are there
    Content: assert(loadfile("mbs.lua", _ENV))('startup', "mbs.lua")

    package.instdat.filemaps["???"] = "/startup/00_mbs.lua"
]]

package.instdat.filemaps["mbs.lua"] = "/mbs.lua"

package.instdat.filemaps["lib/readline.lua"] = "/.mbs/lib/readline.lua"
package.instdat.filemaps["lib/scroll_window.lua"] = "/.mbs/lib/scroll_window.lua"
package.instdat.filemaps["lib/stack_trace.lua"] = "/.mbs/lib/stack_trace.lua"

package.instdat.filemaps["modules/lua.lua"] = "/.mbs/modules/lua.lua"
package.instdat.filemaps["modules/pager.lua"] = "/.mbs/modules/pager.lua"
package.instdat.filemaps["modules/readline.lua"] = "/.mbs/modules/readline.lua"
package.instdat.filemaps["modules/shell.lua"] = "/.mbs/modules/shell.lua"

package.instdat.filemaps["bin/clear.lua"] = "/.mbs/bin/clear.lua"
package.instdat.filemaps["bin/lua.lua"] = "/.mbs/bin/lua.lua"
package.instdat.filemaps["bin/shell-worker.lua"] = "/.mbs/bin/shell-worker.lua"
package.instdat.filemaps["bin/shell.lua"] = "/.mbs/bin/shell.lua"

package.pkgType = "com.github"
package.unicornSpec = "v1.0.0"

return package
