-- Generated by easyunicornpkg ©Commandcracker
-- https://github.com/SquidDev-CC/metis

local package = {}
package.name = "metis"
package.desc = "A collection of libraries for ComputerCraft/CC:Tweaked"
package.instdat = {}
package.instdat.repo_owner = "SquidDev-CC"
package.instdat.repo_name = "metis"
package.instdat.repo_ref = "dev"
package.instdat.filemaps = {}
package.instdat.filemaps["src/metis"] = "/lib/metis"
package.instdat.filemaps["src/metis/argparse.lua"] = "/lib/metis/argparse.lua"
package.instdat.filemaps["src/metis/async.lua"] = "/lib/metis/async.lua"
package.instdat.filemaps["src/metis/crypto"] = "/lib/metis/crypto"
package.instdat.filemaps["src/metis/crypto/sha1.lua"] = "/lib/metis/crypto/sha1.lua"
package.instdat.filemaps["src/metis/fs.lua"] = "/lib/metis/fs.lua"
package.instdat.filemaps["src/metis/input"] = "/lib/metis/input"
package.instdat.filemaps["src/metis/input/keybinding.lua"] = "/lib/metis/input/keybinding.lua"
package.instdat.filemaps["src/metis/input/readline.lua"] = "/lib/metis/input/readline.lua"
package.instdat.filemaps["src/metis/math.lua"] = "/lib/metis/math.lua"
package.instdat.filemaps["src/metis/string.lua"] = "/lib/metis/string.lua"
package.instdat.filemaps["src/metis/string"] = "/lib/metis/string"
package.instdat.filemaps["src/metis/string/fuzzy.lua"] = "/lib/metis/string/fuzzy.lua"
package.instdat.filemaps["src/metis/timer.lua"] = "/lib/metis/timer.lua"
package.pkgType = "com.github"
package.unicornSpec = "v1.0.0"

return package
